config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dogs.urls', namespace='dogs')),
    path('users/', include('users.urls', namespace='users')),
    path('reviews/', include('reviews.urls', namespace='reviews'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path
from dogs.views import (index, BreedListView, DodBreedListView, DodListView, DogCreateView, DogDetailView,
                        DogUpdateView, DogDeleteView, DogDeactivatedListView, dog_toggle_activity, DogSearchListView,
                        BreedSearchListView)
from dogs.apps import DogsConfig
from django.views.decorators.cache import cache_page, never_cache

app_name = DogsConfig.name

urlpatterns = [
    path('', cache_page(60)(index), name='index'),
    path('breeds/', cache_page(60)(BreedListView.as_view()), name='breeds'),
    path('breeds/<int:pk>/dogs/', DodBreedListView.as_view(), name='breed_dogs'),
    path('breeds/search/', BreedSearchListView.as_view(), name='breeds_search'),

    path('dogs/', DodListView.as_view(), name='dogs_list'),
    path('dogs/deactivate/', DogDeactivatedListView.as_view(), name='dogs_deactivated_list'),
    path('dogs/search/', DogSearchListView.as_view(), name='dogs_search'),
    path('dogs/create/', DogCreateView.as_view(), name='dog_create'),
    path('dogs/detail/<int:pk>', DogDetailView.as_view(), name='dog_detail'),
    path('dogs/update/<int:pk>', never_cache(DogUpdateView.as_view()), name='dog_update'),
    path('dogs/toggle/<int:pk>', dog_toggle_activity, name='dog_toggle_activity'),
    path('dogs/delete/<int:pk>', DogDeleteView.as_view(), name='dog_delete'),
]

reviews/urls.py
from django.urls import path

from reviews.apps import ReviewsConfig

from reviews.views import ReviewListView, ReviewDeactivatedListView, ReviewCreateView, ReviewDetailView, \
    ReviewUpdateView, ReviewDeleteView, review_toggle_activity

app_name = ReviewsConfig.name

urlpatterns = [
    path('', ReviewListView.as_view(), name='reviews_list'),
    path('deactivated/', ReviewDeactivatedListView.as_view(), name='reviews_deactivated'),
    path('review/create/', ReviewCreateView.as_view(), name='review_create'),
    path('review/detail/<slug:slug>/', ReviewDetailView.as_view(), name='review_detail'),
    path('review/update/<slug:slug>/', ReviewUpdateView.as_view(), name='review_update'),
    path('review/delete/<slug:slug>/', ReviewDeleteView.as_view(), name='review_delete'),
    path('review/toggle/<slug:slug>/', review_toggle_activity, name='review_toggle_activity'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import UserRegisterView, UserLoginView, UserProfileView, UserLogoutView, UserUpdateView, \
    UserPasswordChangeView, user_generate_new_password_view, UserListView, UserDetailView

app_name = UsersConfig.name

urlpatterns = [
    # Работа с аккаунтом
    path('', UserLoginView.as_view(), name='user_login'),
    path('logout/', UserLogoutView.as_view(), name='user_logout'),
    path('register/', UserRegisterView.as_view(), name='user_register'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('update/', UserUpdateView.as_view(), name='user_update'),
    path('change_password/', UserPasswordChangeView.as_view(), name='user_change_password'),
    path('profile/genpassword/', user_generate_new_password_view, name='user_generate_new_password'),

    # Просмотр других пользователей
    path('all_users/', UserListView.as_view(), name='users_list'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='user_detail')
]

dogs/models.py
from django.db import models
from django.conf import settings

from users.models import NULLABLE


class Breed(models.Model):
    """
    Модель породы собаки
    """
    name = models.CharField(max_length=100, verbose_name='breed')
    description = models.CharField(max_length=1000, verbose_name='description', **NULLABLE)

    def __str__(self):
        """
        Представление модели в строковом виде
        """
        return f'{self.name}'

    class Meta:
        """
        Настройки параметров модели Breed
        """
        verbose_name = 'breed'
        verbose_name_plural = 'breeds'


class Dog(models.Model):
    """
    Модель собаки
    """
    name = models.CharField(max_length=150, verbose_name='Кличка')
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, verbose_name='Порода')
    photo = models.ImageField(upload_to='dogs/', **NULLABLE, verbose_name='Изображение')
    birth_date = models.DateField(**NULLABLE, verbose_name='Дата рождения')
    is_active = models.BooleanField(default=True, verbose_name='Активность')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Хозяин')
    views = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        """
        Представление модели в строковом виде
        """
        return f'{self.name} ({self.breed})'

    class Meta:
        """
        Настройки параметров модели Dog
        """
        verbose_name = 'dog'
        verbose_name_plural = 'dogs'
        # abstract = True
        # app_label = 'dogs'
        # ordering = [-1]
        # permission = []
        # db_table = 'doggies'
        # get_latest_by = 'birth_date'

    def views_count(self):
        """
        Счётчик просмотров модели
        """
        self.views += 1
        self.save()


class DogParent(models.Model):
    """
    Модель собаки-родителя
    """
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)
    name = models.CharField(max_length=150, verbose_name='Кличка Родителя')
    category = models.ForeignKey(Breed, on_delete=models.CASCADE, verbose_name='Порода Родителя')
    birth_date = models.DateField(**NULLABLE, verbose_name='Дата рождения Родителя')

    def __str__(self):
        """
        Представление модели в строковом виде
        """
        return f'{self.name} ({self.breed})'

    class Meta:
        """
        Настройки параметров модели DogParent
        """
        verbose_name = 'parent'
        verbose_name_plural = 'parents'

dogs/forms.py
import datetime

from django import forms

from dogs.models import Dog, DogParent
from users.forms import StyleFromMixin


class DogForm(StyleFromMixin, forms.ModelForm):
    """
    Класс формы DogForm, использующий ModelForm
    """
    class Meta:
        """
        Класс с настройками для модели Dog
        """
        model = Dog
        exclude = ('owner', 'is_active', 'views',)

    def clean_birth_date(self):
        """
        Валидация поля 'birth_date'
        """
        cleaned_data = self.cleaned_data['birth_date']
        if cleaned_data:
            now_year = datetime.datetime.now().year
            if now_year - cleaned_data.year > 35:
                raise forms.ValidationError('Собака должна быть моложе 35 лет')
        return cleaned_data


class DogAdminForm(DogForm):
    """
    Класс, предназначенный для работы в административной части приложения
    """
    class Meta:
        """
        Класс с настройками для модели Dog
        """
        model = Dog
        exclude = ('is_active',)

    # def clean_birth_date(self):
    #     cleaned_birth_date = super().clean_birth_date()
    #     return cleaned_birth_date


class DogParentForm(StyleFromMixin, forms.ModelForm):
    """
    Класс формы DogParentForm, использующий ModelForm
    """
    class Meta:
        """
        Класс с настройками для модели DogParent
        """
        model = DogParent
        fields = '__all__'

dogs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.core.exceptions import PermissionDenied
from django.db.models import Q

from dogs.forms import DogForm, DogParentForm, DogAdminForm
from dogs.models import Breed, Dog, DogParent
from dogs.services import send_views_mail
from users.models import UserRoles


def index(request):
    """
    Представление главной страницы
    """
    context = {
        'object_list': Breed.objects.all()[:3],
        'title': 'Питомник - Главная'
    }
    return render(request, 'dogs/index.html', context)


class BreedListView(LoginRequiredMixin, ListView):
    """
    Представление списка пород собак
    """
    model = Breed
    extra_context = {
        'title': "Все наши породы"
    }
    template_name = 'dogs/breeds.html'
    paginate_by = 3


class BreedSearchListView(LoginRequiredMixin, ListView):
    """
    Результат поискового запроса по породе собак
    """
    model = Breed
    template_name = 'dogs/breeds.html'
    extra_context = {
        'title': 'Результаты поискового запроса'
    }

    def get_queryset(self):
        """
        Получение списка объектов по определенному запросу
        """
        query = self.request.GET.get('q')
        print(query)
        object_list = Breed.objects.filter(
            Q(name__icontains=query)
        )
        return object_list


class DodBreedListView(LoginRequiredMixin, ListView):
    """
    Продставление списка собак определенной породы
    """
    model = Dog
    template_name = 'dogs/dogs.html'
    extra_context = {
        'title': 'Собаки выбранной породы'
    }

    def get_queryset(self):
        """
        Получение списка обЪектов
        """
        queryset = super().get_queryset().filter(breed_id=self.kwargs.get('pk'))
        return queryset


class DodListView(ListView):
    """
    Представление всех собак
    """
    model = Dog
    extra_context = {
        'title': 'Питомник - Все наши собаки',
    }
    template_name = 'dogs/dogs.html'
    paginate_by = 3

    def get_queryset(self):
        """
        Получение списка обЪектов
        """
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True)
        return queryset


class DogDeactivatedListView(LoginRequiredMixin, ListView):
    """
    Представление списка неактивных собак
    """
    model = Dog
    extra_context = {
        'title': 'Питомник - неактивные собаки'
    }
    template_name = 'dogs/dogs.html'

    def get_queryset(self):
        """
        Получение списка обЪектов
        """
        queryset = super().get_queryset()
        if self.request.user.role in [UserRoles.MODERATOR, UserRoles.ADMIN]:
            queryset = queryset.filter(is_active=False)
        if self.request.user.role == UserRoles.USER:
            queryset = queryset.filter(is_active=False, owner=self.request.user)
        return queryset


class DogSearchListView(LoginRequiredMixin, ListView):
    """
    Результаты поискового запроса по кличке собаки
    """
    model = Dog
    template_name = 'dogs/dogs.html'
    extra_context = {
        'title': 'Результаты поискового запроса'
    }

    def get_queryset(self):
        """
        Получение списка обЪектов
        """
        query = self.request.GET.get('q')
        print(query)
        object_list = Dog.objects.filter(
            Q(name__icontains=query), is_active=True,
        )
        return object_list


class DogCreateView(LoginRequiredMixin, CreateView):
    """
    Добавление (создание) собаки
    """
    model = Dog
    form_class = DogForm
    template_name = 'dogs/create_update.html'
    extra_context = {
        'title': 'Добавить собаку'
    }
    success_url = reverse_lazy('dogs:dogs_list')

    def form_valid(self, form):
        """
        Валидация формы, перед добавлением собаки
        """
        if self.request.user.role != UserRoles.USER:
            raise PermissionDenied()
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class DogDetailView(DetailView):
    """
    Представление подробной информации о собаке
    """
    model = Dog
    template_name = 'dogs/detail.html'

    def get_context_data(self, **kwargs):
        """
        Передача дополнительных параметров в контекст шаблона проекта
        """
        context_data = super().get_context_data(**kwargs)
        object_ = self.get_object()
        context_data['title'] = f'Подробная информация {object_}'
        dog_object_increase = get_object_or_404(Dog, pk=object_.pk)
        if object_.owner != self.request.user:
            dog_object_increase.views_count()
        if object_.owner:
            object_owner_email = object_.owner.email
            if dog_object_increase.views % 20 == 0 and dog_object_increase.views != 0:
                send_views_mail(dog_object_increase.name, object_owner_email, dog_object_increase.views)
        return context_data


class DogUpdateView(LoginRequiredMixin, UpdateView):
    """
    Изменение (обновление) собаки
    """
    model = Dog
    template_name = 'dogs/create_update.html'
    extra_context = {
        'title': 'Изменить собаку'
    }

    def get_success_url(self):
        """
        Перенаправление пользователя после успешного обновления объекта
        """
        return reverse('dogs:dog_detail', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        """
        Проверка на соответствие владельца объекта текущему пользователю
        """
        self.object = super().get_object(queryset)
        # if self.object.owner != self.request.user and not self.request.user.is_staff:
        if self.object.owner != self.request.user and self.request.user.role != UserRoles.ADMIN:
            raise PermissionDenied()
        return self.object

    def get_form_class(self):
        """
        Выбор класса формы в зависимости от роли пользователя
        """
        dog_forms = {
            'admin': DogAdminForm,
            'moderator': DogForm,
            'user': DogForm
        }
        user_role = self.request.user.role
        dog_form_class = dog_forms[user_role]
        return dog_form_class

    def get_context_data(self, **kwargs):
        """
        Передача дополнительных параметров в контекст шаблона проекта
        """
        context_data = super().get_context_data(**kwargs)
        DogParentFormset = inlineformset_factory(Dog, DogParent, form=DogParentForm, extra=1)
        if self.request.method == 'POST':
            formset = DogParentFormset(self.request.POST, instance=self.object)
        else:
            formset = DogParentFormset(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        """
        Валидация формы
        """
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class DogDeleteView(PermissionRequiredMixin, DeleteView):
    """
    Удаление собаки
    """
    model = Dog
    template_name = 'dogs/delete.html'
    extra_context = {
        'title': 'Удалить собаку'
    }
    success_url = reverse_lazy('dogs:dogs_list')
    permission_required = 'dogs.delete_dog'
    permission_denied_message = "У Вас нет нужных прав для этого действия!"


def dog_toggle_activity(request, pk):
    """
    Переключения активности объекта "собака" в базе данных
    """
    dog_item = get_object_or_404(Dog, pk=pk)
    if dog_item.is_active:
        dog_item.is_active = False
    else:
        dog_item.is_active = True
    dog_item.save()
    return redirect(reverse('dogs:dogs_list'))

dogs/templates/dogs/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    {% load static %}
</head>
<body>

    <header class="bg-info text-white text-center py-3">
    <h1>Добро пожаловать в приют для собак</h1>
    <p>Помогите нам спасти жизни</p>
    </header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Приют для собак</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dogs:index' %}">Главная</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Информация
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <div class="col text-center">
                    {% if user.is_superuser %}
                    <a class="p-2 btn btn-success" href="/admin/">Админка</a>
                    {% endif %}
                    </div>
                    <div class="col text-center">
                    <a class="dropdown-item" href="{% url 'dogs:breeds' %}">Породы</a>
                    <a class="dropdown-item" href="{% url 'dogs:dogs_list' %}">Собаки</a>
                        {% include 'dogs/includes/inc_search_fields.html' %}
                    <a class="dropdown-item" href="{% url 'reviews:reviews_list' %}">Наши отзывы</a>
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="col text-center">
                    {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'users:users_list' %}">Все пользователи</a>
                        <a class="dropdown-item" href="{% url 'users:user_profile' %}">Профиль</a>
                        <span class="text-muted">{{ user }}</span>
                        <form method="post" action="{% url 'users:user_logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm">Выход</button>
                        </form>
                    {% else %}
                    </div>
                        <a class="dropdown-item" href="{% url 'users:user_login' %}">Вход</a>
                        <a class="dropdown-item" href="{% url 'users:user_register' %}">Регистрация</a>
                    {% endif %}
                </div>
            </li>
        </ul>
    </div>
</nav>

    <main role="main">
        <section class="jumbotron text-center">
            <div class="container">
                <h1 class="jumbotron-heading">{{ title }}</h1>
            </div>
        </section>
    </main>

    <div class="container mt-4">
        <main>
            {% block content %}
            {% endblock %}
        </main>
    </div>

    <footer class="text-center mt-4">
        <p>&copy; 2025 Приют для собак. Все права защищены.</p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

dogs/templates/dogs/breeds.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    {% for object in object_list %}
        {% include 'dogs/includes/inc_breed.html' with object=object %}
    {% endfor %}
</div>
{% include 'dogs/includes/inc_pagination.html' %}
{% endblock %}

dogs/templates/dogs/create.html
{% extends 'dogs/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data" class="row" xmlns="http://www.w3.org/1999/html">
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                {% if object %}
                    Редактирование собаки
                {% else %}
                    Добавление собаки
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                        Сохранить
                    {% else %}
                        Добавить
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

dogs/templates/dogs/create_update.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                {% if object %}
                    Редактирование собаки
                {% else %}
                    Добавление собаки
                {% endif %}
            </div>
            <img class="card-img-top"
                 src="{{ object.photo|dogs_media }}" width="300" height="400"
                 alt="Card image cap">
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-outline-success"
                       value="{% if object %}Сохранить{% else %}Добавить{% endif %}">
                <a href="{% if object %}{% url 'dogs:dog_toggle_activity' object.pk %}{% endif %}"
                class="btn btn-outline-warning float-right">
                {% if object.is_active %}
                Деактивировать
                {% else %}
                Активировать
                {% endif %}
                </a>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'dogs:dogs_list' %}" class="btn btn-primary"><< Назад</a>
            {% if object and user.is_superuser %}
            <a href="{% url 'dogs:dog_delete' object.pk %}" class="btn btn-danger float-right">Удалить</a>
            {% endif %}
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% if not forloop.last %}
                <hr>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

dogs/templates/dogs/delete.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Вы уверены, что хотите удалить собаку?
                {% endif %}
            </div>
            <div class="card-body">
                <img class="card-img-top"
                      src="{{ object.photo|dogs_media }}" width="300" height="320"
                      alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">{{ object.name|title }}</p>
                </div>

                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-danger">
                    {% if object %}
                    Удалить
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
</form>

{% endblock %}

dogs/templates/dogs/detail.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <img class="card-img-top"
            src="{{ object.photo|dogs_media }}" width="300" height="320"
            alt="Card image cap">
        <div class="card-body">
            <p class="card-text">Кличка: {{ object.name|title }}</p>
            <span class="text-muted">Дата рождения: {{ object.birth_date|default:"-" }}</span><br>
            <span class="text-muted">Эл. почта хозяйна: {{ object.owner|default:"Без хозяйна" }}</span><br>
            <span class="text-muted">Имя хозяйна: {{ object.owner.first_name|default:"Не указано" }}</span><br>
            <span class="text-muted">Телефон хозяйна: {{ object.owner.phone|default:"Не указано" }}</span><br>
            <span class="text-muted">Telegram хозяйна: {{ object.owner.telegram|default:"Не указано" }}</span><br>
            <span class="text-muted">Просмотры: {{ object.views }}</span><br>
        </div>
        <div class="card-footer">
            {% if user.is_staff or user == object.owner %}
                <a class="btn btn-link" href="{% url 'dogs:dog_update' object.pk %}">Обновить</a>
                <a class="btn btn-link" href="{% url 'dogs:dog_delete' object.pk %}">Удалить</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

dogs/templates/dogs/dogs.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        {% for object in object_list %}
        {% include 'dogs/includes/inc_dog_card.html' with object=object %}
        {% endfor %}
    </div>
    {% include 'dogs/includes/inc_pagination.html' %}
    <a href="{% url 'dogs:dog_create' %}" class="btn btn-primary m-2 float-left">Добавить собаку</a>
    <a href="{% url 'dogs:dogs_deactivated_list' %}" class="btn btn-secondary m-2 float-right">Неактивные собаки</a>
    <a href="{% url 'dogs:dogs_list' %}" class="btn btn-success m-2 float-right">Активные собаки</a>
</div>
{% endblock %}

dogs/templates/dogs/dogs_search_results.html
<h1> Search Results </h1>

<ul>
    {% for object in object_list %}
    <li>
        {{ object.name }}, {{ object.category }}
    </li>
    {% endfor %}
</ul>

dogs/templates/dogs/home.html
{% extends 'dogs/base.html' %}

{% block content %}
    <h1>Добро пожаловать в приют для собак!</h1>
    <p>Помогите нам заботиться о бездомных собаках.</p>
{% endblock %}

dogs/templates/dogs/index.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    {% for object in object_list %}
        {% include 'dogs/includes/inc_breed.html' with object=object %}
    {% endfor %}
</div>
{% endblock %}