config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dogs.urls', namespace='dogs')),
    path('users/', include('users.urls', namespace='users')),
    path('reviews/', include('reviews.urls', namespace='reviews'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path
from dogs.views import (index, BreedListView, DodBreedListView, DodListView, DogCreateView, DogDetailView,
                        DogUpdateView, DogDeleteView, DogDeactivatedListView, dog_toggle_activity, DogSearchListView,
                        BreedSearchListView)
from dogs.apps import DogsConfig
from django.views.decorators.cache import cache_page, never_cache

app_name = DogsConfig.name

urlpatterns = [
    path('', cache_page(60)(index), name='index'),
    path('breeds/', cache_page(60)(BreedListView.as_view()), name='breeds'),
    path('breeds/<int:pk>/dogs/', DodBreedListView.as_view(), name='breed_dogs'),
    path('breeds/search/', BreedSearchListView.as_view(), name='breeds_search'),

    path('dogs/', DodListView.as_view(), name='dogs_list'),
    path('dogs/deactivate/', DogDeactivatedListView.as_view(), name='dogs_deactivated_list'),
    path('dogs/search/', DogSearchListView.as_view(), name='dogs_search'),
    path('dogs/create/', DogCreateView.as_view(), name='dog_create'),
    path('dogs/detail/<int:pk>', DogDetailView.as_view(), name='dog_detail'),
    path('dogs/update/<int:pk>', never_cache(DogUpdateView.as_view()), name='dog_update'),
    path('dogs/toggle/<int:pk>', dog_toggle_activity, name='dog_toggle_activity'),
    path('dogs/delete/<int:pk>', DogDeleteView.as_view(), name='dog_delete'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import UserRegisterView, UserLoginView, UserProfileView, UserLogoutView, UserUpdateView, \
    UserPasswordChangeView, user_generate_new_password_view, UserListView, UserDetailView

app_name = UsersConfig.name

urlpatterns = [
    # Работа с аккаунтом
    path('', UserLoginView.as_view(), name='user_login'),
    path('logout/', UserLogoutView.as_view(), name='user_logout'),
    path('register/', UserRegisterView.as_view(), name='user_register'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('update/', UserUpdateView.as_view(), name='user_update'),
    path('change_password/', UserPasswordChangeView.as_view(), name='user_change_password'),
    path('profile/genpassword/', user_generate_new_password_view, name='user_generate_new_password'),

    # Просмотр других пользователей
    path('all_users/', UserListView.as_view(), name='users_list'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='user_detail')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

NULLABLE = {'blank': True, 'null': True}


class UserRoles(models.TextChoices):
    """
    Модель роли пользователя
    """
    ADMIN = 'admin', _('admin')
    MODERATOR = 'moderator', _('moderator')
    USER = 'user', _('user')


class User(AbstractUser):
    """
    Модель пользователя
    """
    username = None
    email = models.EmailField(unique=True, verbose_name='Эл. почта')
    role = models.CharField(max_length=9, choices=UserRoles.choices, default=UserRoles.USER)
    first_name = models.CharField(max_length=150, verbose_name='Имя', default='Anonymous')
    last_name = models.CharField(max_length=150, verbose_name='Фамилия', default='Anonymous')
    phone = models.CharField(max_length=35, verbose_name='Номер телефона', **NULLABLE)
    telegram = models.CharField(max_length=150, verbose_name='Telegram', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='Активность')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        """
        Представление модели в строковом виде
        """
        return f'{self.email}'

    class Meta:
        """
        Настройка параметров для модели User
        """
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['id']

users/forms.py
from django import forms

from users.models import User
from users.validators import validate_password
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.contrib.auth import password_validation


class StyleFromMixin:
    """
    Стилизация к полям формы
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserForm(StyleFromMixin, forms.ModelForm):
    """
    Форма пользователя
    """
    class Meta:
        """
        Класс с насторойками для модели User
        """
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar',)


class UserRegisterForm(StyleFromMixin, UserCreationForm):
    """
    Форма регистрации пользователя
    """
    class Meta:
        """
        Класс с настройками для модели User
        """
        model = User
        fields = ('email',)

    def clean_password2(self):
        """
        Проверку корректности введённых паролей пользователем
        """
        cleaned_data = self.cleaned_data
        validate_password(cleaned_data['password1'])
        if cleaned_data['password1'] != cleaned_data['password2']:
            raise forms.ValidationError('Пароли не совпадают.')
        return cleaned_data['password2']


class UserLoginForm(StyleFromMixin, AuthenticationForm):
    """
    Форма логина пользователя
    """
    pass


class UserUpdateForm(StyleFromMixin, forms.ModelForm):
    """
    Форма обновления данных пользователя
    """
    class Meta:
        """
        Класс с настройками для модели User
        """
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'telegram', 'avatar')


class UserPasswordChangeForm(StyleFromMixin, PasswordChangeForm):
    """
    Форма изменения пароля пользователя
    """
    def clean_new_password2(self):
        """
        Изменение пароля
        """
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        validate_password(password1)
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        password_validation.validate_password(password2, self.user)
        return password2

users/views.py
import random
import string

from django.shortcuts import reverse, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from users.models import User
from users.forms import UserRegisterForm, UserLoginForm, UserUpdateForm, UserPasswordChangeForm, UserForm
from users.services import send_new_password, send_register_email


class UserRegisterView(CreateView):
    """
    Представление интерфейса регистрации пользователя
    """
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:user_login')
    template_name = 'users/user_register.html'
    extra_context = {
        'title': 'Регистрация пользователя'
    }

    def form_valid(self, form):
        """
        Валидация формы при регистрации пользователя
        """
        self.object = form.save()
        send_register_email(self.object.email)
        return super().form_valid(form)


class UserLoginView(LoginView):
    """
    Представление интерфейса ввода данных для входа в аккаунт
    """
    template_name = 'users/user_login.html'
    form_class = UserLoginForm
    extra_context = {
        'title': 'Вход в аккаунт'
    }


class UserProfileView(UpdateView):
    """
    Представление профиля пользователя
    """
    model = User
    form_class = UserForm
    template_name = 'users/user_profile_read_only.html'
    extra_context = {
        'title': 'Ваш профиль'
    }

    def get_object(self, queryset=None):
        """
        Проверка соответствия пользователя
        """
        return self.request.user


class UserUpdateView(UpdateView):
    """
    Представление интерфейса для обновления профиля пользователя
    """
    model = User
    form_class = UserUpdateForm
    template_name = 'users/user_update.html'
    success_url = reverse_lazy('users:user_profile')
    extra_context = {
        'title': 'Обновить профиль'
    }

    def get_object(self, queryset=None):
        """
        Представление интерфейса для проверки соответствия пользователя
        """
        return self.request.user


class UserPasswordChangeView(PasswordChangeView):
    """
    Представление интерфейса для изменения пароля пользователя
    """
    form_class = UserPasswordChangeForm
    template_name = 'users/user_change_password.html'
    success_url = reverse_lazy('users:user_profile')
    extra_context = {
        'title': 'Изменение пароля'
    }


class UserLogoutView(LogoutView):
    """
    Представление интерфейса для выхода из аккаунта
    """
    template_name = 'users/user_logout.html'
    extra_context = {
        'title': 'Выход из аккаунта'
    }


class UserListView(LoginRequiredMixin, ListView):
    """
    Представление списка всех пользователей
    """
    model = User
    extra_context = {
        'title': "Питомник. Все наши пользователи"
    }
    template_name = 'users/users.html'
    paginate_by = 3

    def get_queryset(self):
        """
        Фильтрация активных пользователей
        """
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True)
        return queryset


class UserDetailView(DetailView):
    """
    Представление информации профиля пользователя
    """
    model = User
    template_name = 'users/user_detail_view.html'

    def get_context_data(self, **kwargs):
        """
        Передача дополнительных параметров в контекст шаблона проекта
        """
        context_data = super().get_context_data()
        user_obj = self.get_object()
        context_data['title'] = f"Профиль пользователя - {user_obj}"
        return context_data


@login_required
def user_generate_new_password_view(request):
    """
    Представление интерфейса для генерации нового пароля пользователя
    """
    new_password = ''.join(random.sample((string.ascii_letters + string.digits), 12))
    request.user.set_password(new_password)
    request.user.save()
    send_new_password(request.user.email, new_password)
    return redirect(reverse('dogs:index'))

users/templates/users/user_change_password.html
{% extends 'dogs/base.html' %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                Изменение пароля
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_detail_view.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Профиль {{ object.last_name }} {{ object.first_name }}
            </div>
            <img class="card-img-top"
                 src="{{ object.avatar|user_media }}" width="300" height="500"
                 alt="Card image cap">
            <div class="card-body">
                <span class="card-text">Почта: {{ object.email }}</span><br>
                <span class="card-text">Имя: {{ object.first_name|default:"Не указано" }}</span><br>
                <span class="card-text">Фамилия: {{ object.last_name|default:"Не указано" }}</span><br>
                <span class="card-text">Телефон: {{ object.phone|default:"Не указано" }}</span><br>
                <span class="card-text">Telegram: {{ object.telegram|default:"Не указано" }}</span><br>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:users_list' %}" class="btn btn-outline-promary"><< Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_login.html
{% extends 'dogs/base.html' %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Введите данные для входа</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_logout.html
{% extends 'dogs/base.html' %}
{% block content %}
<h1>Вы успешно вышли из вашего аккаунта</h1>
<p>Спасибо за использование нашего сервиса!</p>
<a href="{% url 'users:user_login' %}" >Нажмите сюда, чтобы снова войти</a>
{% endblock %}

users/templates/users/user_profile_read_only.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Мой профиль</div>
            <img class="card-img-top"
            src="{{ user.avatar|user_media }}" width="300" height="700"
            alt="Card Image cap">
            <div class="card-body">
                <span class="card-text">Почта: {{ user.email }}</span><br>
                <span class="card-text">Имя: {{ user.first_name|default:"Не указано" }}</span><br>
                <span class="card-text">Фамилия: {{ user.last_name|default:"Не указано" }}</span><br>
                <span class="card-text">Телефон: {{ user.phone|default:"Не указано" }}</span><br>
                <span class="card-text">Telegram: {{ user.telegram|default:"Не указано" }}</span><br>
                <button class="btn btn-outline-warning">
                    <a class="btn btn-link" href="{% url 'users:user_update' %}">Обновить</a>
                </button>
                <button class="btn btn-outline-warning">
                    <a class="btn btn-link" href="{% url 'users:user_change_password' %}">Изменить пароль</a>
                </button>
                <button class="btn btn-outline-danger float-right">
                    <a class="btn btn-link" href="{% url 'users:user_generate_new_password' %}">Генерация пароля</a>
                </button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_register.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Введите данные для регистрации</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>

</div>
{% endblock %}

users/templates/users/user_update.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Изменить профиль
             </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/users.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        {% for object in object_list %}
        {% include 'users/includes/inc_user_card.html' with object=object %}
        {% endfor %}
    </div>
    {% include 'dogs/includes/inc_pagination.html' %}
</div>
{% endblock %}